---
title: "upllýsingaverkfræði"
author: "jakobina"
date: "2024-10-14"
output: html_document
---
```{r}
library(tidyverse)
library(dplyr)
```

```{r}
library(tidyverse)
```

```{r}
gogn <- mutate(kaupskra_4_, fermetraverd = KAUPVERD / EINFLM)
```

```{r}
#smá REGEX
gogn <- gogn %>% 
  select(matches("^(HEIMILISFANG|POSTNR|SVEITARFELAG|UTGDAG|KAUPVERD|EINFLM|TEGUND|fermetraverd)$"))
print(gogn_valdir)
```

```{r}
#REGEX
gogn2023 <-gogn %>%
  filter(grepl("^2023-", UTGDAG))
```

```{r}
write.csv(gogn2023, "fasteignir2023.csv", row.names = FALSE)
```

```{r}
gogn2023 <- gogn2023 %>%
  group_by(SVEITARFELAG) %>%
  summarise(
    meðal_fermetraverd = round(mean(fermetraverd, na.rm = TRUE),2),
    meðal_stærð = round(mean(EINFLM, na.rm = TRUE),2),
    meðal_verð = round(mean(KAUPVERD, na.rm = TRUE),2),  # Reikna meðaltal af heildarverðinu
    algengasta_tegund = names(sort(table(TEGUND), decreasing = TRUE)[1])
  )
```


```{r}
ny_tafla <- gogn %>%
  mutate(Ar = as.numeric(format(as.Date(UTGDAG, format="%Y-%m-%d"), "%Y"))) %>%
  filter(Ar >= 1999 & Ar <= 2023) %>%
  group_by(SVEITARFELAG, Ar) %>%
  summarise(meðal_fermetraverd = round(mean(fermetraverd, na.rm = TRUE),2)) %>%
  ungroup() %>%
  # Umbreyta í breitt snið þar sem árin verða dálkar
  pivot_wider(names_from = Ar, values_from = meðal_fermetraverd)

# Skoða niðurstöðuna
print(ny_tafla)

```


```{r}
write.csv(ny_tafla, "fasteignirár.csv", row.names = FALSE)
```

