---
title: "Premier League Analysis"
author: "Erlendur Guðnason, Ingvar Auðunarson, Jakob Stefán Ívarsson, Þráinn Ágúst Arnaldsson"
date: "2024-11-04"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

```

*Lesa inn alla pakka*
```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(rvest)
library(dplyr)
library(DBI)
library(RSQLite)
library(shiny)
library(ggplot2)
library(plotly)
library(shinyjs)
library(shinydashboard)
library(DT)
library(sf)          
library(leaflet) 
library(ggimage)
library(here)
```

*Tengjast gagnagrunninum*
```{r}
con <- dbConnect(RSQLite::SQLite(), here("premier_league.db"))


# Skoða hvaða töflur eru í gagnagrunninum
dbListTables(con)



```


*Lesa inn gögn úr töflunni*
```{r}
Games_data <- dbReadTable(con, "Games")

PlayerStats_data <- dbReadTable(con, "Playerstats")

Stadiums_data <- dbReadTable(con, "Stadiums")

Teams_data <- dbReadTable(con, "Teams")

SqliteSequence_data <- dbReadTable(con, "sqlite_sequence")

toflur <- dbReadTable(con, "match_status")


```

```{r}
Games_data <- dbGetQuery(con, "SELECT * FROM Games")
PlayerStats_data <- dbGetQuery(con, "SELECT * FROM PlayerStats")
Stadiums_data <- dbGetQuery(con, "SELECT * FROM Stadiums")
Teams_data <- dbGetQuery(con, "SELECT * FROM Teams")
match_status_data <- dbGetQuery(con, "SELECT * FROM match_status")
```


```{r}
ui <- fluidPage(
  tags$head(tags$style(HTML("
    body.light-mode {background-color: #ffffff; color: #000000;}
    body.dark-mode {background-color: #1e1e1e; color: #e0e0e0;}
    .slider-container, .dropdown-menu, .table, .navbar, .card, .panel {
      background-color: #333333; color: #e0e0e0;
    }
    table.dataframe th, table.dataframe td {
      border: 1px solid #444444; color: #e0e0e0; background-color: #333333;
    }
    table.dataframe th {background-color: #4CAF50; color: white;}
    table.dataframe tr:nth-child(even) {background-color: #2a2a2a;}
    table.dataframe tr:hover {background-color: #444444;}
    .table-container {
      border: 1px solid #4CAF50;
      padding: 15px;
      margin: 10px 0;
      border-radius: 8px;
    }
  "))),

  tags$div(
    style = "background: linear-gradient(135deg, #38003c, #4CAF50); padding: 20px; text-align: center; color: #ffffff; display: flex; align-items: center; justify-content: center;",
    # Title and Dark Mode Toggle
    tags$div(
      h1("Enska Úrvalsdeildin", style = "font-size: 3em; font-weight: bold; margin: 0;"),
      h3("Tímabilið 2019/20", style = "font-size: 1.5em; font-weight: normal; color: #d0d0d0; margin-top: 10px;")
    ),
    
    tags$div(
      style = "position: absolute; top: 20px; right: 20px;",
      checkboxInput("theme_switch", "Dark Mode", value = FALSE)
    )
  ),
  
  tags$script(HTML("
    document.getElementById('theme_switch').addEventListener('change', function() {
      if (this.checked) {
        document.body.classList.add('dark-mode');
        document.body.classList.remove('light-mode');
      } else {
        document.body.classList.add('light-mode');
        document.body.classList.remove('dark-mode');
      }
    });
  ")),

  # Tabs
  tabsetPanel(
    tabPanel("Heim",
             h2("Rýni inn í tímabilið 2019/20"),
             p("Verkefnið er þróað af eftirfarandi höfundum: 
               Erlendur Guðnasson, Ingvar Auðunarson, Jakob Stefán Ívarsson og Þráinn Ágúst Arnaldsson. Það byggir á ítarlegri gagnavinnslu úr fjórum stórum CSV skrám sem samanstanda af mikilvægum upplýsingum úr ensku úrvalsdeildinni og eru tengdar saman í nokkrar töflur í gagnagrunninum premier_league.db. Kóðinn er skrifaður í R, SQL og Python, með örlítilli notkun á Regex til að auðvelda gagnagreiningu og sýna tölfræðilegar niðurstöður."),
             h3("Flipaútskýring"),
             p("Verkefnið býður upp á dökkt- og ljóstþema til að bæta upplifun notenda."),

             h4("Heim"),
             p("Velkomin á aðalsíðuna! Hér færðu yfirsýn yfir tilgang forritsins og möguleikann til að skoða margvíslega tölfræði úr ensku úrvalsdeildinni 2019/20. Notaðu flipana efst til að vafra um tölfræði um stöðutöflur, staðsetningar leikvanga, frammistöðu leikmanna og veðmálaupplýsingar."),
             
             h4("Síðustu ár"),
             p("Þessi síða gerir þér kleift að bera saman lið yfir tímabil og sýnir stigatölur þeirra frá tímabilinu 2010/11 til 2023/24 á línuriti. Hér getur þú valið lið og fylgst með þróun árangurs þeirra í stigum yfir árin, sem veitir yfirlit yfir stöðugleika og frammistöðu þeirra í ensku úrvalsdeildinni.
"),
             
             h4("Stöðutafla"),
             p("Þessi tafla sýnir stigatöfluna fyrir liðin eftir valda leikviku. Þú getur valið leikviku með slider til að sjá hvernig staðan þróast yfir tímabilið. Þú getur einnig skoðað síðustu leiki hvers liðs fyrir valda leikviku og fengið innsýn í árangur þeirra á tímabilinu."),
             
             h4("Staðsetningar"),
             p("Á þessari síðu geturðu skoðað staðsetningu allra leikvanga liða í ensku úrvalsdeildinni 2019/20 á korti með GPS hnitum. Þetta gefur þér möguleika á að sjá landfræðilega dreifingu liða yfir England. Ásamt grafi sem sýnir betur stærðaröð leikvangana."),
             
             h4("Færanýtni"),
             p("Hér eru ýmis tölfræði á scatter-myndritum sem sýna færni leikmanna. Veldu mismunandi gerðir af myndritum til að skoða fjölda marka og mínútna, skot á mark, eða hæstu markaskorara á tímabilinu. Þú getur jafnframt valið tegund framlags, t.d. mörk eða mörk og stoðsendingar samanlagt ef valið er 'Top Goalscorer'."),
             
             h4("BetStatistics"),
             p("Þessi síða býður upp á greiningu á veðmálatölfræði fyrir valið lið. Þú getur séð þróun hagnaðar og taps yfir tímabilið og heildarhagnað í lok þess. Þetta gefur innsýn í veðmálatengdan árangur liðsins og hvort veðmál hafi skilað arði. Gröfin byggja á því að einstaklingur hafi sett 10$ veðmál á hvern einasta leik tiltekins liðs þar sem veðjað var á sigur."),
             
             h4("Dómararýni"),
             p("Á þessari síðu geturðu skoðað ýmsa tölfræði um frammistöðu dómara. Hér eru meðal annars gögn um fjölda brota per spjald, dæmt sigurhlutfall heimaliða og útliða, auk þess sem þú getur séð sigurleiki ákveðinna liða þegar tiltekinn dómari hefur dæmt þá oftast. Þetta gefur áhugaverða innsýn í áhrif dómara á úrslit leikja og á hegðun leikmanna á vellinum."),
             
             h4("Liðin"),
             p("Á þessari síðu er hægt að bera saman tölfræði milli tveggja liða á ýmsum sviðum eins og mörkum, hornum, skotum og brotum, spjöldum og fleira. Þú getur einnig fengið yfirlit yfir meðaltal tölfræðinnar fyrir öll liðin í deildinni. Ef þú vilt sjá heildaryfirlit af öllu þá er hægt að haka við 'Show as table' í hægra horni")
    ),
    tabPanel("Síðustu ár",
  sidebarLayout(
    sidebarPanel(
      selectInput("selected_teams", "Veldu lið:", choices = unique(toflur$Name), multiple = TRUE),
      # Slider to select the season range
      sliderInput("season_range", "Veldu tímabil fyrir töflu:", min = 2010, max = 2024, value = c(2010, 2024), step = 1, sep = "")
    ),
    mainPanel(
      plotOutput("pointsPlot"),
      tableOutput("pointsSummaryTable")
    )
  )
),
    tabPanel("Stöðutafla",
             h2("Tímabilið 2019/20"),
             fluidRow(
               column(5,
                      h3("Stöðutafla"),
                      sliderInput("game_week", "Veldu tímabilsviku:", min = 1, max = 38, value = 1),
                      div(class = "highlighted-table", tableOutput("league_table"))
               ),
               column(5, offset = 1,
                      h3("Síðustu leikir"),
                      selectInput("team_select", "Veldu lið", choices = NULL),
                      sliderInput("num_games", "Veldu fjölda leikja til að sýna:", min = 1, max = 10, value = 5),
                      div(class = "highlighted-table", tableOutput("last_games_table"))
               )
             )
    ),
    tabPanel("Staðsetningar",
             h2("Leikvangar á korti"),
             leafletOutput("stadiums_map"),
             h3("Samanburður á sætisfjölda leikvanga"),
             plotOutput("stadium_capacity_plot")
    ),
    tabPanel("Færanýtni",
             selectInput("plot_choice", "Veldu tegund af scatter plot:", 
                         choices = c("Goals vs. Minutes", "Shots on Target vs. Goals", "Top Goalscorers")),
             conditionalPanel(
               condition = "input.plot_choice == 'Top Goalscorers'",
               radioButtons("goal_type", "Veldu týpu markframlags:", 
                            choices = c("Goals" = "goals", "Goals + Assists" = "goals_assists")),
               sliderInput("top_n_scorers", "Veldu fjölda af markahæstu leikmönnum:", min = 1, max = 251, value = 10)
             ),
             plotlyOutput("efficiency_plot")
    ),
    tabPanel("BetStatistics",
             selectInput("bet_team", "Veldu lið", choices = NULL),
             plotlyOutput("betting_progress"),
             h3("End of Season Profit/Loss"),
             uiOutput("end_season_profit_loss")
    ),
    tabPanel("Dómararýni",
             h2("Dómararýni"),
             plotlyOutput("fouls_per_card_plot"),
             plotlyOutput("win_distribution_pie"),
             plotlyOutput("referee_most_wins_bar")
    ),
    tabPanel("Liðin",
             h2("2019/20 Liða samanburður", style = "display: inline-block;"),
             div(
               style = "float: right; margin-bottom: 10px;",
               actionButton("show_graph", "Show as graph"),
               actionButton("show_table", "Show as table")
             ),
             conditionalPanel(
               condition = "output.view_mode == 'graph'",
               selectInput("comparison_metric", "Veldu samanburðarflokk", 
                           choices = list("Goals Scored" = "goals_scored",
                                          "Goals Conceded" = "goals_conceded",
                                          "Corners Won" = "corners_won",
                                          "Corners Conceded" = "corners_conceded",
                                          "Shots" = "shots",
                                          "Shots on Target" = "shots_on_target",
                                          "Fouls" = "fouls",
                                          "Yellow Cards" = "yellow_cards",
                                          "Red Cards" = "red_cards")),
               fluidRow(
                 column(6, selectInput("team1", "Veldu lið 1", choices = NULL)),
                 column(6, selectInput("team2", "Veldu lið 2", choices = NULL))
               ),
               plotlyOutput("team_metric_plot"),
               h3("Meðaltal yfir tímabilið"),
               tableOutput("average_metric_table")
             ),
             conditionalPanel(
               condition = "output.view_mode == 'table'",
               h3("Meðaltal liðanna yfir tímabilið"),
               tableOutput("all_teams_average_table")
             )
    )
  )
)




```


```{r}
server <- function(input, output, session) {
  
  con <- dbConnect(RSQLite::SQLite(), here("premier_league.db"))

  onStop(function() {
    if (dbIsValid(con)) {
      dbDisconnect(con)
    }
  })
  
  
  stadiums_data <- dbGetQuery(con, "SELECT Team, FDCOUK, City, Stadium, Capacity, Latitude, Longitude, Country FROM Stadiums")
  
  teams_pattern <- "\\b(?:Liverpool|Manchester City|Manchester United|Chelsea|Leicester City|Tottenham Hotspur|Wolverhampton Wanderers|Arsenal|Sheffield United|Burnley|Southampton|Everton|Newcastle United|Crystal Palace|Brighton & Hove Albion|West Ham United|Aston Villa|Bournemouth|Watford|Norwich City)\\b"
  
  Stadiums_data <- stadiums_data %>%
    filter(str_detect(Team, teams_pattern))
  
  Stadiums_data <- Stadiums_data %>%
    mutate(Logo_url = here("Logos", paste0(str_replace_all(Team, " ", "_"), ".png")))
  
  missing_logos <- Stadiums_data %>% filter(!file.exists(Logo_url))
  if (nrow(missing_logos) > 0) {
    warning("Missing logo files for teams: ", paste(missing_logos$Team, collapse = ", "))
  }
  
  Location_data <- st_as_sf(Stadiums_data, coords = c("Longitude", "Latitude"), crs = 4326)
  
  output$stadiums_map <- renderLeaflet({
    leaflet() %>%
      addTiles() %>%
      addMarkers(data = Location_data,
                 lng = ~st_coordinates(geometry)[, 1],
                 lat = ~st_coordinates(geometry)[, 2],
                 icon = ~icons(iconUrl = Logo_url, iconWidth = 30, iconHeight = 30),
                 popup = ~paste("<b>Team:</b>", Team, "<br><b>Stadium:</b>", Stadium, "<br><b>City:</b>", City, "<br><b>Capacity:</b>", Capacity))
  })
  
  stadiums_sorted <- Stadiums_data %>%
    arrange(desc(Capacity))
  
  output$stadium_capacity_plot <- renderPlot({
    ggplot(stadiums_sorted, aes(x = reorder(Stadium, Capacity), y = Capacity)) +
      geom_image(aes(image = Logo_url), size = 0.05, by = "width") + 
      coord_flip() +
      labs(title = "Stærð valla í Ensku Úrvalsdeildinni (2019/2020 Season)",
           x = "Völlur",
           y = "Stærð (fjöldi sæta)") +
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0.5))
  })
  
  
observe({
  teams <- dbGetQuery(con, "SELECT DISTINCT HomeTeam FROM Games ORDER BY HomeTeam ASC")
  updateSelectInput(session, "team_select", choices = teams$HomeTeam)
  updateSelectInput(session, "bet_team", choices = teams$HomeTeam)
})

league_table_data <- reactive({
  game_week <- input$game_week
 
  query <- paste0("
    WITH GameResults AS (
      SELECT 
        HomeTeam AS Team, 
        FTHG - FTAG AS GoalDifference,
        CASE WHEN FTR = 'H' THEN 3 WHEN FTR = 'D' THEN 1 ELSE 0 END AS Points,
        CASE WHEN FTR = 'H' THEN 1 ELSE 0 END AS Win,
        CASE WHEN FTR = 'D' THEN 1 ELSE 0 END AS Draw,
        CASE WHEN FTR = 'A' THEN 1 ELSE 0 END AS Loss
      FROM Games
      WHERE GW <= ", game_week, "
      UNION ALL
      SELECT 
        AwayTeam AS Team, 
        FTAG - FTHG AS GoalDifference,
        CASE WHEN FTR = 'A' THEN 3 WHEN FTR = 'D' THEN 1 ELSE 0 END AS Points,
        CASE WHEN FTR = 'A' THEN 1 ELSE 0 END AS Win,
        CASE WHEN FTR = 'D' THEN 1 ELSE 0 END AS Draw,
        CASE WHEN FTR = 'H' THEN 1 ELSE 0 END AS Loss
      FROM Games
      WHERE GW <= ", game_week, "
    )
    SELECT 
      Team,
      COUNT(*) AS Played,
      SUM(Win) AS W,
      SUM(Draw) AS D,
      SUM(Loss) AS L,
      SUM(GoalDifference) AS `+/-`,
      SUM(Points) AS PTS
    FROM GameResults
    GROUP BY Team
    ORDER BY PTS DESC, `+/-` DESC
  ")

  league_table_df <- dbGetQuery(con, query)
  
  league_table_df$POS <- seq_len(nrow(league_table_df))
  league_table_df
})

output$league_table <- renderTable({
  league_data <- league_table_data()
  if (is.null(league_data)) {
    return(data.frame(Message = "No data available for the selected game week"))
  }
  league_data[, c("POS", "Team", "Played", "W", "D", "L", "+/-", "PTS")]
}, rownames = FALSE)

output$last_games_table <- renderTable({
  team <- input$team_select
  num_games <- input$num_games
  game_week <- input$game_week  # Use the selected game week as the upper limit
  
  query <- paste0("
    SELECT 
      GW AS GameWeek, 
      CASE 
        WHEN HomeTeam = '", team, "' THEN AwayTeam 
        ELSE HomeTeam 
      END AS Opponent,
      CASE 
        WHEN HomeTeam = '", team, "' THEN FTHG || ' - ' || FTAG
        ELSE FTAG || ' - ' || FTHG 
      END AS Goals,
      CASE 
        WHEN (HomeTeam = '", team, "' AND FTR = 'H') OR (AwayTeam = '", team, "' AND FTR = 'A') THEN 'W'
        WHEN FTR = 'D' THEN 'D'
        ELSE 'L'
      END AS Result
    FROM Games 
    WHERE (HomeTeam = '", team, "' OR AwayTeam = '", team, "') 
      AND GW <= ", game_week, "
    ORDER BY GW DESC 
    LIMIT ", num_games
  )

  last_games <- dbGetQuery(con, query)
  last_games
}, rownames = FALSE)



  
  output$efficiency_plot <- renderPlotly({
  fig <- NULL
  
  if (input$plot_choice == "Goals vs. Minutes") {
    # Query for Goals vs. Minutes plot
    query <- "SELECT PLAYER, MIN, G FROM PlayerStats WHERE MIN > 0 AND G > 0"
    plot_data <- dbGetQuery(con, query)
    fig <- ggplot(plot_data, aes(x = MIN, y = G, label = PLAYER)) +
      geom_point(color = "#1f77b4", size = 3, alpha = 0.7) +  # Blue points with transparency
      labs(title = "Goals vs. Minutes Played", x = "Minutes Played", y = "Goals") +
      theme_minimal(base_size = 15) +
      theme(plot.title = element_text(size = 20, face = "bold", hjust = 0.5))

  } else if (input$plot_choice == "Shots on Target vs. Goals") {
    # Query for Shots on Target vs. Goals plot
    query <- "SELECT PLAYER, SOG, G FROM PlayerStats WHERE SOG > 0"
    plot_data <- dbGetQuery(con, query)
    fig <- ggplot(plot_data, aes(x = SOG, y = G, label = PLAYER)) +
      geom_point(color = "#ff7f0e", size = 3, alpha = 0.7) +  # Orange points with transparency
      labs(title = "Shots on Target vs. Goals", x = "Shots on Target", y = "Goals") +
      theme_minimal(base_size = 15) +
      theme(plot.title = element_text(size = 20, face = "bold", hjust = 0.5))

  } else if (input$plot_choice == "Top Goalscorers") {
    # Set the number of top scorers
    top_n <- input$top_n_scorers
    
    if (input$goal_type == "goals") {
      # Query for top goalscorers based on goals only
      query <- paste0(
        "SELECT PLAYER, G 
         FROM PlayerStats 
         WHERE G > 0 
         ORDER BY G DESC 
         LIMIT ", top_n
      )
      plot_data <- dbGetQuery(con, query)
      fig <- ggplot(plot_data, aes(x = reorder(PLAYER, -G), y = G, label = PLAYER)) +
        geom_bar(stat = "identity", fill = "blue") +
        labs(title = paste("Top", top_n, "Goalscorers"), x = "Player", y = "Goals") +
        theme(axis.text.x = element_text(angle = 45, hjust = 1))
      
    } else {
      # Query for top goal contributors based on goals + assists
      query <- paste0(
        "SELECT PLAYER, (G + ASST) AS Contributions 
         FROM PlayerStats 
         WHERE (G + ASST) > 0 
         ORDER BY Contributions DESC 
         LIMIT ", top_n
      )
      plot_data <- dbGetQuery(con, query)
      fig <- ggplot(plot_data, aes(x = reorder(PLAYER, -Contributions), y = Contributions, label = PLAYER)) +
        geom_bar(stat = "identity", fill = "purple") +
        labs(title = paste("Top", top_n, "Goal Contributors (Goals + Assists)"), x = "Player", y = "Goals + Assists") +
        theme(axis.text.x = element_text(angle = 45, hjust = 1))
    }
  }

  ggplotly(fig) %>% layout(
    title = list(text = fig$labels$title, x = 0.5, font = list(size = 24, color = "darkblue")),
    xaxis = list(title = fig$labels$x, titlefont = list(size = 18)),
    yaxis = list(title = fig$labels$y, titlefont = list(size = 18))
  )
})
  
  observe({
  teams_query <- "SELECT DISTINCT Name FROM match_status ORDER BY Name ASC"
  teams <- dbGetQuery(con, teams_query)$Name
  
  updateSelectInput(session, "selected_teams", choices = teams)
})

output$pointsPlot <- renderPlot({
  query <- paste0(
    "SELECT Name, season, Pts, status_type
     FROM match_status  
     WHERE Name IN ('", paste(input$selected_teams, collapse = "', '"), "') 
     AND season != '2024-2025'"
  )
  
  plot_data <- dbGetQuery(con, query)
  
  ggplot(plot_data, aes(x = season, y = Pts, color = Name, linetype = status_type, group = interaction(Name, status_type))) +
    geom_line(linewidth = 1) +
    scale_linetype_manual(values = c("All" = "solid", "Home" = "dashed", "Away" = "dotted")) +
    labs(x = "Tímabil/Season", y = "Heildarstig", title = "Heildarstig eftir valin lið") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
})

output$pointsSummaryTable <- renderTable({
  # Return NULL if no teams are selected
  if (is.null(input$selected_teams) || length(input$selected_teams) == 0) {
    return(NULL)
  }
  
  season_min <- input$season_range[1]
  season_max <- input$season_range[2]
  
  summary_query <- paste0(
    "SELECT Name, season,
            SUM(CASE WHEN status_type = 'All' THEN Pts ELSE 0 END) AS All_Points,
            SUM(CASE WHEN status_type = 'Home' THEN Pts ELSE 0 END) AS Home_Points,
            SUM(CASE WHEN status_type = 'Away' THEN Pts ELSE 0 END) AS Away_Points
     FROM match_status 
     WHERE Name IN ('", paste(input$selected_teams, collapse = "', '"), "')
     AND season BETWEEN '", season_min, "-2010' AND '", season_max, "-2024'
     GROUP BY Name, season
     ORDER BY Name, season"
  )
  
  summary_data <- dbGetQuery(con, summary_query)
  
  summary_data
})




  observe({
    print("Database connection status:")
    print(dbIsValid(con))
  })
  
 output$betting_progress <- renderPlotly({
  team <- input$bet_team
  team_games_query <- paste0(
    "SELECT 
       ROW_NUMBER() OVER (ORDER BY Date) AS Week,  -- Use row numbering instead of GameWeek if Date exists
       CASE 
         WHEN HomeTeam = '", team, "' AND FTR = 'H' THEN (B365H * 10) - 10
         WHEN AwayTeam = '", team, "' AND FTR = 'A' THEN (B365A * 10) - 10
         ELSE -10 
       END AS Profit
     FROM Games 
     WHERE HomeTeam = '", team, "' OR AwayTeam = '", team, "'"
  )
  
  team_games <- dbGetQuery(con, team_games_query)
  
  # Calculate cumulative profit
  team_games$Cumulative_Profit <- cumsum(team_games$Profit)
  
  # Plot using plotly
  fig <- plot_ly()
  for (i in 2:nrow(team_games)) {
    segment_color <- ifelse(team_games$Cumulative_Profit[i-1] >= 0, "green", "red")
    fig <- fig %>%
      add_trace(
        x = team_games$Week[(i-1):i], 
        y = team_games$Cumulative_Profit[(i-1):i], 
        type = 'scatter', 
        mode = 'lines+markers',
        line = list(color = segment_color, width = 2),
        marker = list(color = segment_color, size = 8),
        hoverinfo = "text",
        text = paste("Week:", team_games$Week[(i-1):i], "<br>Profit:", round(team_games$Cumulative_Profit[(i-1):i], 2)),
        showlegend = FALSE
      )
  }
  
  fig <- fig %>%
    layout(
      title = paste("Uppsafnaður hagnaður/tap fyrir ", team),
      xaxis = list(title = "Leikvika"),
      yaxis = list(title = "Uppsafnaður hagnaður/tap ($)")
    )
  
  fig
})


  
  output$end_season_profit_loss <- renderUI({
  req(input$bet_team)
  
  team <- input$bet_team
  season_profit_query <- paste0(
    "SELECT 
       SUM(CASE 
         WHEN HomeTeam = '", team, "' AND FTR = 'H' THEN (B365H * 10) - 10
         WHEN AwayTeam = '", team, "' AND FTR = 'A' THEN (B365A * 10) - 10
         ELSE -10 
       END) AS Cumulative_Profit
     FROM Games 
     WHERE HomeTeam = '", team, "' OR AwayTeam = '", team, "'"
  )
  
  season_profit <- dbGetQuery(con, season_profit_query)$Cumulative_Profit
  
  color <- ifelse(season_profit >= 0, "green", "red")
  HTML(paste0(
    '<div style="border: 2px solid ', color, '; padding: 15px; margin: 15px 0; border-radius: 8px; background-color: ', color, '10;">',
    '<h4 style="color: ', color, ';"><i class="fa fa-dollar-sign"></i> Lok tímabils hagnaður/tap</h4>',
    '<p style="font-size: 1.2em; color: ', color, ';">$', round(season_profit, 2), '</p>',
    '</div>'
  ))
})
  
  
  
  output$fouls_per_card_plot <- renderPlotly({
    query <- "
    SELECT 
        Referee,
        SUM(HF + AF) AS Total_Fouls,
        SUM(HY + AY) AS Total_Yellow_Cards,
        SUM(HR + AR) AS Total_Red_Cards
    FROM 
        games
    GROUP BY 
        Referee;
    "
    referee_data <- dbGetQuery(con, query)
    referee_data$Total_Cards <- referee_data$Total_Yellow_Cards + referee_data$Total_Red_Cards
    referee_data$Fouls_Per_Card <- referee_data$Total_Fouls / referee_data$Total_Cards

    fig <- ggplot(referee_data, aes(x = reorder(Referee, -Fouls_Per_Card), y = Fouls_Per_Card)) +
      geom_bar(stat = "identity") +
      labs(title = "Brot á hvert spjald að meðaltali fyrir hvern og einn dómara",
           x = "Dómari",
           y = "Brot á hvert spjald") +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
      
    ggplotly(fig)
  })

  output$win_distribution_pie <- renderPlotly({
    query <- "
    SELECT 
        SUM(CASE WHEN FTR = 'H' THEN 1 ELSE 0 END) AS Total_Home_Team_Wins,
        SUM(CASE WHEN FTR = 'D' THEN 1 ELSE 0 END) AS Total_Draws,
        SUM(CASE WHEN FTR = 'A' THEN 1 ELSE 0 END) AS Total_Away_Team_Wins
    FROM 
        games;
    "
    win_data <- dbGetQuery(con, query)
    
    plot_ly(
      labels = c("Heima lið vann", "Jafntefli", "Úti lið vann"),
      values = c(win_data$Total_Home_Team_Wins, win_data$Total_Draws, win_data$Total_Away_Team_Wins),
      type = "pie",
      textinfo = "label+percent",
      insidetextorientation = "radial"
    ) %>% layout(title = "Dreifing á sigrum dæmdra leikja")
  })

  output$referee_most_wins_bar <- renderPlotly({
    query <- "
    SELECT Referee, WinningTeam, MAX(Wins) AS Wins FROM (
        SELECT Referee, 
               CASE WHEN FTR = 'H' THEN HomeTeam ELSE AwayTeam END AS WinningTeam, 
               COUNT(*) AS Wins
        FROM Games
        WHERE FTR IN ('H', 'A')
        GROUP BY Referee, WinningTeam
    )
    GROUP BY Referee
    ORDER BY Wins DESC;
    "
    referee_most_wins <- dbGetQuery(con, query)
    
    fig <- ggplot(referee_most_wins, aes(x = Referee, y = Wins, fill = WinningTeam)) +
      geom_bar(stat = "identity") +
      labs(title = "Sigursælasta lið hvers dómara",
           x = "Dómari", y = "Fjöldi sigra") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
    
    ggplotly(fig)
  })
  
  
  
  
  
  
  

observe({
  teams <- dbGetQuery(con, "SELECT DISTINCT HomeTeam FROM Games ORDER BY HomeTeam ASC")
  
  updateSelectInput(session, "team1", choices = teams$HomeTeam)
  
  updateSelectInput(session, "team2", choices = rev(teams$HomeTeam))
})

get_combined_weekly_metric <- function(team1, team2, metric) {
  query <- paste0("SELECT GW, HomeTeam, AwayTeam, FTHG, FTAG, HC, AC, \"HS\", \"AS\", HST, AST, HF, AF, HY, AY, HR, AR 
                   FROM Games WHERE (HomeTeam = '", team1, "' OR AwayTeam = '", team1, "' OR 
                                    HomeTeam = '", team2, "' OR AwayTeam = '", team2, "') ORDER BY GW")
  team_games <- dbGetQuery(con, query)

  team1_metric <- team_games %>%
      filter(HomeTeam == team1 | AwayTeam == team1) %>%
      mutate(Metric_Value = switch(metric,
                                   "goals_scored" = ifelse(HomeTeam == team1, FTHG, FTAG),
                                   "goals_conceded" = ifelse(HomeTeam == team1, FTAG, FTHG),
                                   "corners_won" = ifelse(HomeTeam == team1, HC, AC),
                                   "corners_conceded" = ifelse(HomeTeam == team1, AC, HC),
                                   "shots" = ifelse(HomeTeam == team1, `HS`, `AS`),
                                   "shots_on_target" = ifelse(HomeTeam == team1, HST, AST),
                                   "fouls" = ifelse(HomeTeam == team1, HF, AF),
                                   "yellow_cards" = ifelse(HomeTeam == team1, HY, AY),
                                   "red_cards" = ifelse(HomeTeam == team1, HR, AR))) %>%
      group_by(GW) %>%
      summarize(Total_Metric_Value = sum(Metric_Value, na.rm = TRUE)) %>%
      mutate(Team = team1)

  team2_metric <- team_games %>%
      filter(HomeTeam == team2 | AwayTeam == team2) %>%
      mutate(Metric_Value = switch(metric,
                                   "goals_scored" = ifelse(HomeTeam == team2, FTHG, FTAG),
                                   "goals_conceded" = ifelse(HomeTeam == team2, FTAG, FTHG),
                                   "corners_won" = ifelse(HomeTeam == team2, HC, AC),
                                   "corners_conceded" = ifelse(HomeTeam == team2, AC, HC),
                                   "shots" = ifelse(HomeTeam == team2, `HS`, `AS`),
                                   "shots_on_target" = ifelse(HomeTeam == team2, HST, AST),
                                   "fouls" = ifelse(HomeTeam == team2, HF, AF),
                                   "yellow_cards" = ifelse(HomeTeam == team2, HY, AY),
                                   "red_cards" = ifelse(HomeTeam == team2, HR, AR))) %>%
      group_by(GW) %>%
      summarize(Total_Metric_Value = sum(Metric_Value, na.rm = TRUE)) %>%
      mutate(Team = team2)

  combined_metric <- bind_rows(team1_metric, team2_metric)
  combined_metric
}

  view_mode <- reactiveVal("graph")
  
  observeEvent(input$show_graph, {
    view_mode("graph")
  })
  
  observeEvent(input$show_table, {
    view_mode("table")
  })
  
  get_team_average_metric <- function(team_name, metric) {
    query <- paste0("SELECT HomeTeam, AwayTeam, FTHG, FTAG, HC, AC, \"HS\", \"AS\", HST, AST, HF, AF, HY, AY, HR, AR 
                     FROM Games WHERE HomeTeam = '", team_name, "' OR AwayTeam = '", team_name, "'")
    team_games <- dbGetQuery(con, query)

    avg_metric <- team_games %>%
        mutate(Metric_Value = switch(metric,
                                     "goals_scored" = ifelse(HomeTeam == team_name, FTHG, FTAG),
                                     "goals_conceded" = ifelse(HomeTeam == team_name, FTAG, FTHG),
                                     "corners_won" = ifelse(HomeTeam == team_name, HC, AC),
                                     "corners_conceded" = ifelse(HomeTeam == team_name, AC, HC),
                                     "shots" = ifelse(HomeTeam == team_name, `HS`, `AS`),
                                     "shots_on_target" = ifelse(HomeTeam == team_name, HST, AST),
                                     "fouls" = ifelse(HomeTeam == team_name, HF, AF),
                                     "yellow_cards" = ifelse(HomeTeam == team_name, HY, AY),
                                     "red_cards" = ifelse(HomeTeam == team_name, HR, AR))) %>%
        summarize(Average_Metric_Value = mean(Metric_Value, na.rm = TRUE)) %>%
        mutate(Team = team_name)

    avg_metric
  }
  
  get_all_teams_average <- function() {
    teams <- dbGetQuery(con, "SELECT DISTINCT HomeTeam FROM Games ORDER BY HomeTeam ASC")$HomeTeam
    
    
    all_teams_average <- data.frame(
      Team = character(),
      `Goals Scored` = numeric(),
      `Goals Conceded` = numeric(),
      `Corners Won` = numeric(),
      `Corners Conceded` = numeric(),
      `Shots` = numeric(),
      `Shots on Target` = numeric(),
      `Fouls` = numeric(),
      `Yellow Cards` = numeric(),
      `Red Cards` = numeric(),
      stringsAsFactors = FALSE
    )
    
    
    for (team in teams) {
      avg_goals_scored <- get_team_average_metric(team, "goals_scored")$Average_Metric_Value
      avg_goals_conceded <- get_team_average_metric(team, "goals_conceded")$Average_Metric_Value
      avg_corners_won <- get_team_average_metric(team, "corners_won")$Average_Metric_Value
      avg_corners_conceded <- get_team_average_metric(team, "corners_conceded")$Average_Metric_Value
      avg_shots <- get_team_average_metric(team, "shots")$Average_Metric_Value
      avg_shots_on_target <- get_team_average_metric(team, "shots_on_target")$Average_Metric_Value
      avg_fouls <- get_team_average_metric(team, "fouls")$Average_Metric_Value
      avg_yellow_cards <- get_team_average_metric(team, "yellow_cards")$Average_Metric_Value
      avg_red_cards <- get_team_average_metric(team, "red_cards")$Average_Metric_Value

      
      all_teams_average <- rbind(all_teams_average, data.frame(
        Team = team,
        `Goals Scored` = avg_goals_scored,
        `Goals Conceded` = avg_goals_conceded,
        `Corners Won` = avg_corners_won,
        `Corners Conceded` = avg_corners_conceded,
        `Shots` = avg_shots,
        `Shots on Target` = avg_shots_on_target,
        `Fouls` = avg_fouls,
        `Yellow Cards` = avg_yellow_cards,
        `Red Cards` = avg_red_cards,
        stringsAsFactors = FALSE
      ))
    }
    
    all_teams_average
  }

  
  output$view_mode <- reactive(view_mode())

  
  output$team_metric_plot <- renderPlotly({
    req(input$team1, input$team2, input$comparison_metric, view_mode() == "graph")
    combined_metric <- get_combined_weekly_metric(input$team1, input$team2, input$comparison_metric)
    
    fig <- plot_ly(combined_metric, x = ~GW, y = ~Total_Metric_Value, color = ~Team, type = 'scatter', mode = 'lines+markers') %>%
      layout(
        title = paste("Comparison of", input$comparison_metric, "between", input$team1, "and", input$team2),
        xaxis = list(title = "Leikvika"),
        yaxis = list(title = "Fjöldi"),
        legend = list(title = list(text = "Lið"))
      )
    
    fig
  })

  
  output$average_metric_table <- renderTable({
    req(input$team1, input$team2, input$comparison_metric, view_mode() == "graph")
    
    team1_avg <- get_team_average_metric(input$team1, input$comparison_metric)
    team2_avg <- get_team_average_metric(input$team2, input$comparison_metric)
    
    average_table <- bind_rows(team1_avg, team2_avg)
    average_table <- average_table %>%
      select(Team, Average_Metric_Value) %>%
      rename("Team" = Team, "Average" = Average_Metric_Value)
    
    average_table
  })

  
  output$all_teams_average_table <- renderTable({
    req(view_mode() == "table")
    
    all_teams_average <- get_all_teams_average()
    all_teams_average
  })
  
  
  
  
  
observe({
  teams <- dbGetQuery(con, "SELECT DISTINCT HomeTeam FROM Games ORDER BY HomeTeam ASC")
  updateSelectInput(session, "team_select", choices = teams$HomeTeam)
  updateSelectInput(session, "bet_team", choices = teams$HomeTeam)
})


league_table_data <- reactive({
  game_week <- input$game_week
  
  
  query <- paste0("
    WITH GameResults AS (
      SELECT 
        HomeTeam AS Team, 
        FTHG - FTAG AS GoalDifference,
        CASE WHEN FTR = 'H' THEN 3 WHEN FTR = 'D' THEN 1 ELSE 0 END AS Points,
        CASE WHEN FTR = 'H' THEN 1 ELSE 0 END AS Win,
        CASE WHEN FTR = 'D' THEN 1 ELSE 0 END AS Draw,
        CASE WHEN FTR = 'A' THEN 1 ELSE 0 END AS Loss
      FROM Games
      WHERE GW <= ", game_week, "
      UNION ALL
      SELECT 
        AwayTeam AS Team, 
        FTAG - FTHG AS GoalDifference,
        CASE WHEN FTR = 'A' THEN 3 WHEN FTR = 'D' THEN 1 ELSE 0 END AS Points,
        CASE WHEN FTR = 'A' THEN 1 ELSE 0 END AS Win,
        CASE WHEN FTR = 'D' THEN 1 ELSE 0 END AS Draw,
        CASE WHEN FTR = 'H' THEN 1 ELSE 0 END AS Loss
      FROM Games
      WHERE GW <= ", game_week, "
    )
    SELECT 
      Team,
      COUNT(*) AS Played,
      SUM(Win) AS W,
      SUM(Draw) AS D,
      SUM(Loss) AS L,
      SUM(GoalDifference) AS `+/-`,
      SUM(Points) AS PTS
    FROM GameResults
    GROUP BY Team
    ORDER BY PTS DESC, `+/-` DESC
  ")

  
  league_table_df <- dbGetQuery(con, query)
  
  
  league_table_df$POS <- seq_len(nrow(league_table_df))
  league_table_df
})


output$league_table <- renderTable({
  league_data <- league_table_data()
  if (is.null(league_data)) {
    return(data.frame(Message = "No data available for the selected game week"))
  }
  league_data[, c("POS", "Team", "Played", "W", "D", "L", "+/-", "PTS")]
}, rownames = FALSE)


output$last_games_table <- renderTable({
  team <- input$team_select
  num_games <- input$num_games
  game_week <- input$game_week  
  
  
  query <- paste0("
    SELECT 
      GW AS GameWeek, 
      CASE 
        WHEN HomeTeam = '", team, "' THEN AwayTeam 
        ELSE HomeTeam 
      END AS Opponent,
      CASE 
        WHEN HomeTeam = '", team, "' THEN FTHG || ' - ' || FTAG
        ELSE FTAG || ' - ' || FTHG 
      END AS Goals,
      CASE 
        WHEN (HomeTeam = '", team, "' AND FTR = 'H') OR (AwayTeam = '", team, "' AND FTR = 'A') THEN 'W'
        WHEN FTR = 'D' THEN 'D'
        ELSE 'L'
      END AS Result
    FROM Games 
    WHERE (HomeTeam = '", team, "' OR AwayTeam = '", team, "') 
      AND GW <= ", game_week, "
    ORDER BY GW DESC 
    LIMIT ", num_games
  )

  
  last_games <- dbGetQuery(con, query)
  last_games
}, rownames = FALSE)
  

  outputOptions(output, "view_mode", suspendWhenHidden = FALSE)
}

```



```{r}
shinyApp(ui, server)
```